apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-6kxh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-6kxh
    app.kubernetes.io/part-of: tkwch-fix-0075-0041-app
  name: devfile-sample-6kxh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-6kxh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-6kxh
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0041-tenant/tkwch-fix-0075-0041-app/devfile-sample-6kxh@sha256:c6609ee66dad6ed5f4348fdc463b37eeb694b24d38afacc28adc263b52456f09
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
